global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'ada'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'ada'
          environment: 'production'
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['node:9100']
        labels:
          application: 'node'
          environment: 'production'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']