import type { SectionHologramConfig, SectionId } from "./types";
import { MAX_PARTICLE_COUNT } from "./types";

const ADA_GLB = "/glb/ada.glb";
const ADA_GLB1 = "/glb/bb8.glb";
const EARTH_GLB = "/glb/earth.glb";
const HANDSHAKE_GLB = "/glb/handshake.glb";
const VIETNAM_GLB = "/glb/vietnam.glb";

/**
 * One entry per homepage section, in scroll order. All sections currently
 * point at the same model (`ada.glb`) — swap `url` per entry once per-service
 * GLBs (Web / Mobile / Enterprise / AI) exist; the transition machinery
 * already supports morphing between different models.
 */
export const SECTION_ORDER: SectionId[] = [
  "hero",
  "about",
  "services",
  "partners",
  "people",
  "techstack",
  "why",
  "contact",
];

// Ring params only apply when shape: "ring" — glb sections keep this
// harmless placeholder since every section shares one config shape.
const UNUSED_RING = {
  ringRadius: 3,
  ringThickness: 0.3,
  ringDepthJitter: 0.15,
  ringRippleCount: 10,
  ringRippleAmp: 0.08,
  ringTiltX: -0.5,
};

export const SECTION_CONFIG: Record<SectionId, SectionHologramConfig> = {
  hero: {
    shape: "glb",
    url: ADA_GLB,
    color: "#3f6099",
    particleCount: MAX_PARTICLE_COUNT,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.6,
    light2Color: "#8bb4d5",
    light2Intensity: 1.0,
    modelX: 0,
    modelY: -2.1,
    modelScale: 1,
    autoRotateSpeed: 8,
    bobAmp: 0,
    ...UNUSED_RING,
    mouseGlowColor: "#ffada7",
  },
  about: {
    shape: "glb",
    url: EARTH_GLB,
    color: "#3d5c92",
    particleCount: MAX_PARTICLE_COUNT,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.5,
    light2Color: "#8bb4d5",
    light2Intensity: 1.05,
    modelX: -2.8,
    modelY: -2.2,
    modelScale: 1.5,
    autoRotateSpeed: 8,
    bobAmp: 0,
    ...UNUSED_RING,
    mouseGlowColor: "#aecaff",
  },
  services: {
    shape: "ring",
    url: ADA_GLB,
    color: "#4a7fd0",
    particleCount: 6000,
    // Ambient floor high enough to avoid dark patches on the side facing
    // away from both lights, but not so high everything flattens to near-
    // max brightness (that read as pale/washed out with a light color).
    ambient: 0.7,
    light1Color: "#ffffff",
    light1Intensity: 1.55,
    light2Color: "#7fb0e0",
    light2Intensity: 1.15,
    modelX: -0,
    modelY: 0.5,
    modelScale: 1,
    autoRotateSpeed: 2.2,
    bobAmp: 0.16,
    ringRadius: 3,
    ringThickness: 0.8,
    ringDepthJitter: 0.2,
    ringRippleCount: 14,
    ringRippleAmp: 0.09,
    ringTiltX: -Math.PI / 3,
    mouseGlowColor: "#a7c4ff",
  },
  partners: {
    shape: "glb",
    url: HANDSHAKE_GLB,
    color: "#3d5c92",
    particleCount: MAX_PARTICLE_COUNT + 200000,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.5,
    light2Color: "#8bb4d5",
    light2Intensity: 1.0,
    modelX: 0,
    modelY: -2,
    modelScale: 2,
    autoRotateSpeed: 0,
    bobAmp: 0,
    ...UNUSED_RING,
    mouseGlowColor: "#aecaff",
  },
  people: {
    shape: "glb",
    url: VIETNAM_GLB,
    color: "#3a5e97",
    particleCount: MAX_PARTICLE_COUNT,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.55,
    light2Color: "#8bb4d5",
    light2Intensity: 1.1,
    modelX: -2.6,
    modelY: -1.3,
    modelScale: 1,
    autoRotateSpeed: 0,
    bobAmp: 0,
    ...UNUSED_RING,
    mouseGlowColor: "#aecaff",
  },
  techstack: {
    shape: "ring",
    url: ADA_GLB1,
    color: "#38609f",
    particleCount: 6000,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.6,
    light2Color: "#7fb0e0",
    light2Intensity: 1.2,
    modelX: 0,
    modelY: -0.5,
    modelScale: 1,
    autoRotateSpeed: 0.6,
    bobAmp: 0.18,
    ringRadius: 3.6,
    ringThickness: 0.8,
    ringDepthJitter: 10.12,
    ringRippleCount: 18,
    ringRippleAmp: 0.15,
    ringTiltX: Math.PI / 2,
    mouseGlowColor: "#a7c4ff",
  },
  why: {
    shape: "ring",
    url: ADA_GLB,
    color: "#3d5c92",
    particleCount: 6000,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.5,
    light2Color: "#8bb4d5",
    light2Intensity: 1.05,
    modelX: 0,
    modelY: -1.0,
    modelScale: 1,
    autoRotateSpeed: 0.4,
    bobAmp: 0.18,
    ringRadius: 3.6,
    ringThickness: 0.8,
    ringDepthJitter: 1.12,
    ringRippleCount: 18,
    ringRippleAmp: 0.15,
    ringTiltX: Math.PI / 2,
    mouseGlowColor: "#aecaff",
  },
  contact: {
    shape: "ring",
    url: ADA_GLB1,
    color: "#3f6099",
    particleCount: 4500,
    ambient: 0.2,
    light1Color: "#ffffff",
    light1Intensity: 1.55,
    light2Color: "#8bb4d5",
    light2Intensity: 1.0,
    modelX: 2.3,
    modelY: -1.3,
    modelScale: 1,
    autoRotateSpeed: 0.5,
    bobAmp: 0.12,
    ringRadius: 2.6,
    ringThickness: 0.5,
    ringDepthJitter: 0.18,
    ringRippleCount: 8,
    ringRippleAmp: 0.2,
    ringTiltX: -0.3,
    mouseGlowColor: "#aecaff",
  },
};
